### ISSUE TITLE
Lessc plugin need  to be able to process more than one file

### ISSUE THREAD

**Issue by ipolevoy** [javalite/activeweb#223]
Case: there is a site public and private layouts. Need to be able to generate public and private CSS files in the same build without using Maven profiles

**Comment by ipolevoy** [comment]
completed, but cannot make tests pass on Jenkins/Windows. 
Tests in: `org/javalite/lessc/maven/IntegrationTest.java` are ignored for now

**Comment by ipolevoy** [comment]
See http://s18009742.onlinehome-server.com:8080/job/activeweb-build/78/console

**Comment by ipolevoy** [comment]
Also, see class Test.java on Jenkins at `/c/Users/Administrator`

**Comment by codezion** [comment]
Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:2.9:descriptor (default-descriptor) on project activeweb-lessc-maven-plugin: Error extracting plugin descriptor: 'No mojo definitions were found for plugin: org.javalite:activeweb-lessc-maven-plugin.'

I have done all I could figure out to freeze builds but it seems to be impossible. Old releases miss core features and there are no new releases. Think, you found a bug in your own code, but can not fix it because of activeweb is not possible to build again. Every time it takes day or more for 5 minute fix.

I am thinking what is next step to get version control in use in activeweb projects. Is there any better solution than this: Copy all code out of github to local disc, create own version control (it can not be git so my selection is bzr) and build system (mvn is obvious failure if requires internet, but what to use instead). Then nobody in internet can break the build. Then periodically copy new version to local version control and if build is broken, revert to last working local version. This is very good, but it takes some time to set up local build system that do not depend on internet. There must be some way to freeze builds. How you do it?

**Comment by codezion** [comment]
An how to fix that build error?

**Comment by codezion** [comment]
Thanks. Somebody changed something and the build error in tests disappeared (removed all tests?)
So it builds. But now it do not run. There was similar recently. There is null pointer issue somewhere deep into.

java.lang.ExceptionInInitializerError
        at org.javalite.activeweb.ControllerRunner.<init>(ControllerRunner.java:41)
        at org.javalite.activeweb.RequestDispatcher.<init>(RequestDispatcher.java:42)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:374)

**Comment by ipolevoy** [comment]
@codezion , as  you can see from commits related to this issue, I'm struggling with a build on Windows. I'm ignoring integration tests again. This plugin works as expected but for some reason integration tests break on Windows.

**Comment by ipolevoy** [comment]
@codezion , the last commit fixed the build: http://s18009742.onlinehome-server.com:8080/job/activeweb-build/81/
