### ISSUE TITLE
How to configure my service 

### ISSUE THREAD

**Issue by Typografikon** [javalite/activeweb#274]
Hi, I want to use dependency injection in  ActiveWeb and I deal with service configuration. I wish to configure service using values from request. Lets say I have MyService and i want to pass configuration values HttpSupport.getRealPath("/") and RequestUtils.header("Host") to the service. Is it possible? Not sure about service lifecycle etc.

Motivation is to set document root and domain name automatically to the service. There is probably better way to do this. If so, please fix my intentions :-) I know only static configuration via environment values loaded with jndi lokup from contaner, but this requires to add new environment values to the container and I try to avoid adding special configuration for MyService.

**Comment by ipolevoy** [comment]
@Typografikon , there is a pretty good dependency injection already built  into the framework, and we use it on all our commercial projects. The docs are here: http://javalite.io/dependency_injection
and the Kitchensink has a working example: https://github.com/javalite/kitchensink. 

Basically, it uses Google Guice instead of Spring, and allows you to replace real services with mocks during tests. Here is a controller using a service: https://github.com/javalite/kitchensink/blob/master/src/main/java/app/controllers/InjectionController.java
and here is a test that uses a mock of the same service: https://github.com/javalite/kitchensink/blob/master/src/test/java/app/controllers/InjectionControllerSpec.java

The same can be done in a controller filter. In other words, you would declare a private instance variable on a filter like this: 

```java
public class FooFilter extends HttpSupportFilter {
    @Inject
    private YourService yourService;
    @Override
    public void before() {
        yourService.setPath(getRealPath("/"));
        yourService.setHost(header("host"));
    }
}
```
This will set the values on your service.  The class `HttpSupportFilter` already has all the necesary methods to deal with HTTP parameters and headers, so no need to use `RequestUtils` or `HttpSupport` directly. 

After that, bind this filter to [controllers or specific controllers](http://javalite.io/controller_filters#adding-global-filters)

**WORD OF CAUTION: **

The path and header will be set on your service, which is probably an (eager) singleton. This means that multiple requests will be overwriting each other's values - be careful with that.

**Comment by ipolevoy** [comment]
Ondřej, also if you explain better what your ultimate goal is, I will be able to give you better guidance.

**Comment by Typografikon** [comment]
Thanks, it works nice! I just missed idea to use HttpSupportFilter for service configuring. 

Sure I know about singleton and values overwriting issue.

BTW: I believe there is mistake in docs because theres is no 

`setInjector(Guice.createInjector(...))`

in http://javalite.io/dependency_injection#injection-of-module-into-the-application

**Comment by ipolevoy** [comment]
@Typografikon , this is correct. The `setInjector(Guice.createInjector(...))` is deprecated because it causes issues during tests. Use the `getInjector()` instead. This method is not called during tests, so you will not accidentally initiate a "production" module in tests.

**Comment by ipolevoy** [comment]
I will close this issue because it is more  of a question. You can continue commenting here though.

**Comment by ipolevoy** [comment]
@Typografikon I switched the Kitchensink example to `getInjector()`, please see here: https://github.com/javalite/kitchensink/blob/master/src/main/java/app/config/AppBootstrap.java

**Comment by Typografikon** [comment]
I use activeweb 1.13 and when I use getInjector() I got null service instance and injector creates no service instance. When switched to setInjector() in init() method everything works fine. Should I use setInjector() or getInjector() in activeweb 1.13?

**Comment by ipolevoy** [comment]
activeweb 1.13 does not have getInjector(). It is recommended that  you get a latest snapshot: http://repo.javalite.io/org/javalite/activeweb/1.14-SNAPSHOT/ and use the `getInjector()`. The `setInjector()` will be removed in future versions. We were planning to cut a  new release this week, but delaying because of CI issues. I hope we will get a new release early next week or sooner.

**Comment by ipolevoy** [comment]
https://github.com/javalite/activeweb/issues/277

**Comment by Typografikon** [comment]
Igor, thanks for clarification.
